export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_DENIED = "FETCH_USERS_DENIED";

export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_DENIED = "FETCH_POSTS_DENIED";

export const SAVE_FETCH_POST_REQUEST = "SAVE_FETCH_POSTS_REQUEST";
export const SAVE_FETCH_POST_SUCCESS = "SAVE_FETCH_POSTS_SUCCESS";
export const SAVE_FETCH_POST_DENIED = "SAVE_FETCH_POSTS_DENIED";

export const GET_POSTS_BY_USER_ID = "GET_POSTS_BY_USER_ID";
export const CLEAN_POSTS_BY_USER_ID = "CLEAN_POSTS_BY_USER_ID"